name: fyp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: 2.16.1


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.1
  flutter_image_slideshow: any
  image_picker: any
  get: ^4.6.1
  rflutter_alert: ^2.0.4
  simple_animations: ^1.3.3
  flutter_spinkit: ^5.0.0
  font_awesome_flutter: ^9.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_core:
  firebase_auth:
  firebase_database:
  firebase_storage:
  cloud_firestore:
  flutter_launcher_icons: "^0.9.2"
  email_validator:


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon-logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo-foreground.png"

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - images/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf

    - family: Lobster
      fonts:
        - asset: fonts/Lobster-Regular.ttf

